## Preprocessing

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [6]:
# Determine the number of unique values in each column.
types = application_df.dtypes.index.tolist()
application_df[types].nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts for binning
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_count[app_type_count < 600].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts for binning
class_count = application_df['CLASSIFICATION'].value_counts()
class_count.head(50)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
C2190        1
C4200        1
C2600        1
C5200        1
C1370        1
Name: CLASSIFICATION, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [13]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = application_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

X_train_scaled.shape

(25724, 42)

## Compile, Train and Evaluate the Model

In [19]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

hidden_node1 = 90
hidden_node2 = 30
hidden_node3 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node1, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 90)                3870

 dense_5 (Dense)             (None, 30)                2730

 dense_6 (Dense)             (None, 30)                930

 dense_7 (Dense)             (None, 1)                 31

=================================================================
Total params: 7,561
Trainable params: 7,561
Non-trainable params: 0
_________________________________________________________________

In [20]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [21]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5686 - accuracy: 0.7219
Epoch 2/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5549 - accuracy: 0.7298
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5517 - accuracy: 0.7308
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5505 - accuracy: 0.7323
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5490 - accuracy: 0.7324
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5473 - accuracy: 0.7329
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7318
Epoch 8/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5461 - accuracy: 0.7332
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5459 - accuracy: 0.7343
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5454 - accuracy: 0.7342
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5442 - accuracy: 0.7355
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5439 - accuracy: 0.7359
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5436 - accuracy: 0.7353
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7350
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7366
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7362
Epoch 17/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5422 - accuracy: 0.7357
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5417 - accuracy: 0.7366
Epoch 19/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7363
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7369
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7374
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7368
Epoch 23/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7366
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5405 - accuracy: 0.7369
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5406 - accuracy: 0.7376
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7367
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7374
Epoch 28/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5396 - accuracy: 0.7369
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5397 - accuracy: 0.7370
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7378
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5392 - accuracy: 0.7371
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5393 - accuracy: 0.7373
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5387 - accuracy: 0.7377
Epoch 34/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5389 - accuracy: 0.7381
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5391 - accuracy: 0.7372
Epoch 36/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5383 - accuracy: 0.7374
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7379
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7378
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7379
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7383
Epoch 41/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5377 - accuracy: 0.7377
Epoch 42/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5381 - accuracy: 0.7383
Epoch 43/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5375 - accuracy: 0.7374
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5373 - accuracy: 0.7379
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5376 - accuracy: 0.7379
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5371 - accuracy: 0.7378
Epoch 47/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5367 - accuracy: 0.7376
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7393
Epoch 49/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5366 - accuracy: 0.7390
Epoch 50/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5369 - accuracy: 0.7378

In [22]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5593 - accuracy: 0.7285 - 559ms/epoch - 2ms/step
Loss: 0.5593483448028564, Accuracy: 0.7285131216049194

I did not achieve an accuracy score above 75%. I will search for better optimizations below.

In [23]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value= 90,
        step=5), activation=activation, input_dim=input_features))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=30,
            step=5),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [24]:
# Import keras_tuner
!pip install keras-tuner
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=50,
    hyperband_iterations=2)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting keras-tuner
  Downloading keras_tuner-1.1.3-py3-none-any.whl (135 kB)
     |████████████████████████████████| 135 kB 8.9 MB/s
Collecting kt-legacy
  Downloading kt_legacy-1.0.4-py3-none-any.whl (9.6 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (1.21.6)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (21.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (2.23.0)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (2.9.1)
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (7.9.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (2.6.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.7.5)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (2.0.10)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (5.1.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (57.4.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.2.0)
Collecting jedi>=0.10
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 49.3 MB/s
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.10->ipython->keras-tuner) (0.8.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (0.2.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->keras-tuner) (3.0.9)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->keras-tuner) (0.7.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (2022.9.24)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (1.24.3)
Requirement already satisfied: grpcio>=1.24.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.50.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.38.3)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.4.6)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (3.19.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.6.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.0.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.8.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (2.14.1)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.3.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (3.4.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (4.9)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from markdown>=2.6.8->tensorboard->keras-tuner) (4.13.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (3.10.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (3.2.2)
Installing collected packages: jedi, kt-legacy, keras-tuner
Successfully installed jedi-0.18.1 keras-tuner-1.1.3 kt-legacy-1.0.4

In [25]:
 # Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=50,validation_data=(X_test_scaled,y_test))

Trial 180 Complete [00h 02m 23s]
val_accuracy: 0.7330612540245056

Best val_accuracy So Far: 0.7341107726097107
Total elapsed time: 01h 35m 51s

In [26]:
model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5542 - accuracy: 0.7341 - 578ms/epoch - 2ms/step
Loss: 0.5541797280311584, Accuracy: 0.7341107726097107

In [27]:
best_params = tuner.get_best_hyperparameters()[0]
best_params.values

{'activation': 'tanh',
 'first_units': 66,
 'num_layers': 3,
 'units_0': 26,
 'units_1': 21,
 'units_2': 6,
 'units_3': 21,
 'units_4': 26,
 'tuner/epochs': 50,
 'tuner/initial_epoch': 17,
 'tuner/bracket': 3,
 'tuner/round': 3,
 'tuner/trial_id': '0138'}

In [28]:
# Export our model to HDF5 file
model.save('AlphabetSoupCharity_Optimization_Trial1.h5')

Overview:
- The purpose of this analysis was to explore applying a deep learning model in order to predict the most successful ventures to fund. Using a neural network model, I attempted to predict the success of potential ventures with 75% accuracy or higher.


Data Preprocessing:
- The target variable in this model is the "IS_SUCCESSFUL" column
- The feature variables in this model are: APPLICATION_TYPE, AFFILIATION, CLASSIFICATION, USE_CASE, ORGANIZATION, STATUS, INCOME_AMT, SPECIAL_CONSIDERATIONS, and ASK_AMT.
- Variables that were dropped were EIN and NAME


Compiling, Training, and Evaluating the Model:
- I chose 3 hidden relu layers and 1 sigmoid output layer. For the first relu layer, I chose 90 nodes. For the second and third relu layers, I chose 30 nodes. I tried different combinations of layers and nodes and this combination gave me the best results. Eventually I decided to proceed with optimizing the model before further adjusting the layers.
- Initially I was not able to achieve the target performance (>75% accuracy). After further optimization, I was able to get a little closer to the 75% accuracy mark, but was ultimately unable to achieve this.
- I initially let the keras_tuner run with only 20 epochs, which took just over an hour to complete. The results were still below 75%, so I increased the epochs to 50. This took a long time to complete. I went through a few different trials after the initial optimization to adjust the hyperparameters. Ultimately the increases to the overall accuracy were marginal.

Summary:
- Overall, my deep learning model achieved an accuracy of 73.4%. I did not have any luck with adjusting the hyperparameters and activation methods to improve my results. The only alternative recommendations I have are to try increasing the number of epochs. Another idea I had was to use the .getdummies function on the 'NAME' column and include that in the data I use for the model. However, I believe that would increase the time for the keras_tuner to run. It was already taking over an hour for each optimization analysis. If I had more time, I would explore these alternatives to see if they can increase the accuracy of the model.