<a href="https://colab.research.google.com/github/joh10935/deep-learning-challenge/blob/main/CharityFunding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
app_cat = application_df.dtypes.index.tolist()
application_df[app_cat].nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_count[app_type_count < 600].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
Other      804
T8         737
T7         725
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_count = application_df['CLASSIFICATION'].value_counts()
class_count.head(50)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
C2190        1
C4200        1
C2600        1
C5200        1
C1370        1
Name: CLASSIFICATION, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_count[class_count<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = application_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

X_train_scaled.shape

(25724, 42)

## Compile, Train and Evaluate the Model

In [31]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

hidden_node1 = 40
hidden_node2 = 60
hidden_node3 = 10

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node1, activation='relu', input_dim=input_features))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node2, activation='relu'))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_node3, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_16 (Dense)            (None, 40)                1720

 dense_17 (Dense)            (None, 60)                2460

 dense_18 (Dense)            (None, 10)                610

 dense_19 (Dense)            (None, 1)                 11

=================================================================
Total params: 4,801
Trainable params: 4,801
Non-trainable params: 0
_________________________________________________________________

In [32]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [33]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=200)

Epoch 1/200
804/804 [==============================] - 2s 1ms/step - loss: 0.5709 - accuracy: 0.7201
Epoch 2/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5548 - accuracy: 0.7277
Epoch 3/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5513 - accuracy: 0.7296
Epoch 4/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5496 - accuracy: 0.7303
Epoch 5/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5488 - accuracy: 0.7320
Epoch 6/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5482 - accuracy: 0.7317
Epoch 7/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5473 - accuracy: 0.7321
Epoch 8/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5466 - accuracy: 0.7332
Epoch 9/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5458 - accuracy: 0.7332
Epoch 10/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5455 - accuracy: 0.7355
Epoch 11/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5446 - accuracy: 0.7350
Epoch 12/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5448 - accuracy: 0.7353
Epoch 13/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5443 - accuracy: 0.7337
Epoch 14/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5438 - accuracy: 0.7337
Epoch 15/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5433 - accuracy: 0.7354
Epoch 16/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5434 - accuracy: 0.7343
Epoch 17/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5431 - accuracy: 0.7346
Epoch 18/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5424 - accuracy: 0.7360
Epoch 19/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5428 - accuracy: 0.7341
Epoch 20/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5425 - accuracy: 0.7352
Epoch 21/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5423 - accuracy: 0.7347
Epoch 22/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5412 - accuracy: 0.7361
Epoch 23/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7354
Epoch 24/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5417 - accuracy: 0.7354
Epoch 25/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5411 - accuracy: 0.7364
Epoch 26/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5406 - accuracy: 0.7374
Epoch 27/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5409 - accuracy: 0.7360
Epoch 28/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5407 - accuracy: 0.7362
Epoch 29/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7359
Epoch 30/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7373
Epoch 31/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.7365
Epoch 32/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5402 - accuracy: 0.7372
Epoch 33/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7366
Epoch 34/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7366
Epoch 35/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7367
Epoch 36/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7375
Epoch 37/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7376
Epoch 38/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5387 - accuracy: 0.7379
Epoch 39/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5390 - accuracy: 0.7372
Epoch 40/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7379
Epoch 41/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7375
Epoch 42/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5388 - accuracy: 0.7373
Epoch 43/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7377
Epoch 44/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7374
Epoch 45/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7377
Epoch 46/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5382 - accuracy: 0.7381
Epoch 47/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5379 - accuracy: 0.7380
Epoch 48/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5381 - accuracy: 0.7374
Epoch 49/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5373 - accuracy: 0.7391
Epoch 50/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5375 - accuracy: 0.7381
Epoch 51/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5377 - accuracy: 0.7381
Epoch 52/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5378 - accuracy: 0.7382
Epoch 53/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5375 - accuracy: 0.7380
Epoch 54/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7386
Epoch 55/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 56/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7382
Epoch 57/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5372 - accuracy: 0.7381
Epoch 58/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7391
Epoch 59/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7381
Epoch 60/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7391
Epoch 61/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7388
Epoch 62/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5363 - accuracy: 0.7386
Epoch 63/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7389
Epoch 64/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7398
Epoch 65/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5362 - accuracy: 0.7388
Epoch 66/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5363 - accuracy: 0.7394
Epoch 67/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5365 - accuracy: 0.7395
Epoch 68/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7394
Epoch 69/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7398
Epoch 70/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7393
Epoch 71/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7388
Epoch 72/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5354 - accuracy: 0.7396
Epoch 73/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7394
Epoch 74/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 75/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7400
Epoch 76/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7400
Epoch 77/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7405
Epoch 78/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7402
Epoch 79/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7393
Epoch 80/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5356 - accuracy: 0.7388
Epoch 81/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5352 - accuracy: 0.7403
Epoch 82/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7396
Epoch 83/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5351 - accuracy: 0.7398
Epoch 84/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7400
Epoch 85/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7388
Epoch 86/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7396
Epoch 87/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5353 - accuracy: 0.7402
Epoch 88/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7407
Epoch 89/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5348 - accuracy: 0.7400
Epoch 90/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5347 - accuracy: 0.7404
Epoch 91/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7393
Epoch 92/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7398
Epoch 93/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7402
Epoch 94/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5347 - accuracy: 0.7395
Epoch 95/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7393
Epoch 96/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7397
Epoch 97/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7397
Epoch 98/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7410
Epoch 99/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7405
Epoch 100/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7403
Epoch 101/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7403
Epoch 102/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5342 - accuracy: 0.7408
Epoch 103/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5344 - accuracy: 0.7402
Epoch 104/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7405
Epoch 105/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7410
Epoch 106/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7408
Epoch 107/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7408
Epoch 108/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7404
Epoch 109/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7411
Epoch 110/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7411
Epoch 111/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5336 - accuracy: 0.7410
Epoch 112/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5337 - accuracy: 0.7399
Epoch 113/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5341 - accuracy: 0.7402
Epoch 114/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7400
Epoch 115/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7400
Epoch 116/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7404
Epoch 117/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7403
Epoch 118/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7407
Epoch 119/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5341 - accuracy: 0.7407
Epoch 120/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7408
Epoch 121/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5337 - accuracy: 0.7411
Epoch 122/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5333 - accuracy: 0.7409
Epoch 123/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7406
Epoch 124/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7400
Epoch 125/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7413
Epoch 126/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7407
Epoch 127/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7408
Epoch 128/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7412
Epoch 129/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5336 - accuracy: 0.7399
Epoch 130/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7409
Epoch 131/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7410
Epoch 132/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7416
Epoch 133/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7413
Epoch 134/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7403
Epoch 135/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7407
Epoch 136/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7413
Epoch 137/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5329 - accuracy: 0.7413
Epoch 138/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7406
Epoch 139/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7406
Epoch 140/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7412
Epoch 141/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7408
Epoch 142/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7411
Epoch 143/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7416
Epoch 144/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7401
Epoch 145/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5325 - accuracy: 0.7408
Epoch 146/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7409
Epoch 147/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7404
Epoch 148/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7408
Epoch 149/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7409
Epoch 150/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7413
Epoch 151/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7411
Epoch 152/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7410
Epoch 153/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7416
Epoch 154/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7412
Epoch 155/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7418
Epoch 156/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7411
Epoch 157/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5322 - accuracy: 0.7411
Epoch 158/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7413
Epoch 159/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7418
Epoch 160/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7416
Epoch 161/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7414
Epoch 162/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7418
Epoch 163/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7414
Epoch 164/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7420
Epoch 165/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5324 - accuracy: 0.7417
Epoch 166/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5319 - accuracy: 0.7410
Epoch 167/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7421
Epoch 168/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7418
Epoch 169/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7416
Epoch 170/200
804/804 [==============================] - 2s 2ms/step - loss: 0.5318 - accuracy: 0.7420
Epoch 171/200
804/804 [==============================] - 1s 2ms/step - loss: 0.5318 - accuracy: 0.7411
Epoch 172/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7425
Epoch 173/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7413
Epoch 174/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7415
Epoch 175/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7414
Epoch 176/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7418
Epoch 177/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5310 - accuracy: 0.7417
Epoch 178/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7416
Epoch 179/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7417
Epoch 180/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7417
Epoch 181/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7422
Epoch 182/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7418
Epoch 183/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7417
Epoch 184/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7410
Epoch 185/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5311 - accuracy: 0.7419
Epoch 186/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7417
Epoch 187/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7423
Epoch 188/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 189/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7413
Epoch 190/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5312 - accuracy: 0.7416
Epoch 191/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7414
Epoch 192/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7423
Epoch 193/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7421
Epoch 194/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5314 - accuracy: 0.7416
Epoch 195/200
804/804 [==============================] - 1s 1ms/step - loss: 0.5309 - accuracy: 0.7419
Epoch 196/200

In [34]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5741 - accuracy: 0.7296 - 329ms/epoch - 1ms/step
Loss: 0.5740953683853149, Accuracy: 0.7295626997947693

In [35]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value= 90,
        step=5), activation=activation, input_dim=input_features))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=30,
            step=5),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [37]:
# Import keras_tuner
!pip install keras-tuner
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=50,
    hyperband_iterations=2)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting keras-tuner
  Downloading keras_tuner-1.1.3-py3-none-any.whl (135 kB)
     |████████████████████████████████| 135 kB 6.4 MB/s
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (7.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (2.23.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (21.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (1.21.6)
Collecting kt-legacy
  Downloading kt_legacy-1.0.4-py3-none-any.whl (9.6 kB)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (2.9.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.2.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.7.5)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (57.4.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (5.1.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (4.8.0)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (2.0.10)
Collecting jedi>=0.10
  Downloading jedi-0.18.1-py2.py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 57.1 MB/s
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.10->ipython->keras-tuner) (0.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (0.2.5)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (1.15.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->keras-tuner) (3.0.9)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->keras-tuner) (0.7.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (2022.9.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (1.24.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.8.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.4.6)
Requirement already satisfied: grpcio>=1.24.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.50.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.3.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.6.1)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.38.3)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (2.14.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (3.19.6)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (3.4.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.2.8)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (5.2.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from markdown>=2.6.8->tensorboard->keras-tuner) (4.13.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (3.10.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (4.1.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (3.2.2)
Installing collected packages: jedi, kt-legacy, keras-tuner
Successfully installed jedi-0.18.1 keras-tuner-1.1.3 kt-legacy-1.0.4

In [38]:
 # Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=20,validation_data=(X_test_scaled,y_test))

Trial 180 Complete [00h 01m 16s]
val_accuracy: 0.7334110736846924

Best val_accuracy So Far: 0.73399418592453
Total elapsed time: 01h 01m 29s

In [39]:
model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5544 - accuracy: 0.7340 - 443ms/epoch - 2ms/step
Loss: 0.5543714761734009, Accuracy: 0.73399418592453

In [40]:
# Export our model to HDF5 file
model.save('AlphabetSoupCharity.h5')